@resume_api_gateway_HostAddress = http://localhost:5189

GET {{resume_api_gateway_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{resume_api_gateway_HostAddress}}/api/Resumes?limit=100&skip=0
Authorization: Bearer {{access_token}}
Accept: application/json

###

POST {{resume_api_gateway_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password"
}

###
